/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/core/tenants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Provision a new tenant organisation
     * @description Creates a new isolated tenant within the Abren ERP platform. A tenant represents a single organisation whose data is fully segregated from other tenants at the database level.
     *
     *     **Business rules:**
     *     - Tenant names must be unique across the platform.
     *     - A newly provisioned tenant is immediately active.
     *
     *     **Note:** This endpoint does not require authentication in the initial bootstrap phase but should be restricted to super-admin roles in production.
     */
    post: operations["create_tenant_api_v1_core_tenants_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/core/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a user within the current tenant
     * @description Registers a new user under the authenticated caller's tenant. The user receives a hashed password and is immediately active.
     *
     *     **Required permission:** `core:manage_users`
     *
     *     **Business rules:**
     *     - Email addresses must be unique within the tenant.
     *     - Passwords are hashed with bcrypt before storage.
     *
     *     **Error scenarios:**
     *     - `409 Conflict` — a user with the same email already exists.
     *     - `401 Unauthorized` — missing or invalid Bearer token.
     *     - `403 Forbidden` — caller lacks `core:manage_users` permission.
     */
    post: operations["create_user_api_v1_core_users_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/core/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bootstrap tenant and admin user in one step
     * @description Atomic one-time setup endpoint that provisions a new tenant and creates an initial administrator user in a single transaction. This is the recommended entry point for onboarding a new organisation.
     *
     *     **Sequence:**
     *     1. Provisions the tenant with the given name.
     *     2. Creates the admin user within that tenant.
     *
     *     **Business rules:**
     *     - Tenant name must be unique.
     *     - Admin email must be a valid email address.
     *     - This endpoint is unauthenticated (bootstrap scenario).
     *
     *     **Error scenarios:**
     *     - `400 Bad Request` — tenant name already taken or invalid input.
     *     - `422 Unprocessable Entity` — request body fails schema validation.
     */
    post: operations["setup_erp_api_v1_core_setup_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/core/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve the current user's profile
     * @description CQRS read-path endpoint that returns the profile of the authenticated user based on the JWT `sub` claim.
     *
     *     **Required permission:** Any authenticated user.
     *
     *     **Error scenarios:**
     *     - `401 Unauthorized` — missing or invalid Bearer token.
     *     - `404 Not Found` — user record no longer exists.
     */
    get: operations["read_users_me_api_v1_core_users_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate and obtain JWT tokens
     * @description Standard **OAuth 2.0 Resource Owner Password Credentials** login. Accepts a username (email) and password via `application/x-www-form-urlencoded`, validates the credentials against the user store, and returns a JWT access token plus an optional refresh token.
     *
     *     **Token structure:**
     *     - `access_token` — short-lived JWT containing `sub` (user ID), `tenant_id`, `email`, `roles`, and `permissions` claims.
     *     - `refresh_token` — long-lived JWT (7 days) for silent renewal.
     *
     *     **Authentication:** This endpoint requires **no Bearer token** — it is the authentication entry point.
     *
     *     **Error scenarios:**
     *     - `401 Unauthorized` — email not found or password mismatch.
     *     - `422 Unprocessable Entity` — missing username or password field.
     */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh an expired access token
     * @description Exchanges a valid **refresh token** for a new access / refresh token pair.  Use this endpoint to maintain user sessions without re-prompting for credentials.
     *
     *     **Business rules:**
     *     - The provided token must have `type: refresh` in its payload.
     *     - Refresh tokens expire after 7 days.
     *     - A new refresh token is issued on every call (token rotation).
     *
     *     **Error scenarios:**
     *     - `401 Unauthorized` — token is expired, malformed, or is an access token instead of a refresh token.
     */
    post: operations["refresh_token_api_v1_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/accounting/journal-entries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new journal entry with line items
     * @description Creates a double-entry journal entry in **DRAFT** status with one or more debit/credit line items.  Each line references a GL account from the Chart of Accounts and an amount in the specified currency.
     *
     *     **Required permission:** `accounting:create_entry`
     *
     *     **Business rules:**
     *     - The entry is created in DRAFT status and must be explicitly posted.
     *     - Each line must reference an active GL account.
     *     - Multi-currency lines are converted to the base currency using the prevailing exchange rate.
     *     - The entry number is auto-generated (format: `JV-XXXXXXXX`).
     *
     *     **Idempotency:** Supports the `Idempotency-Key` header.
     *
     *     **Error scenarios:**
     *     - `400 Bad Request` — invalid account ID or currency code.
     *     - `403 Forbidden` — caller lacks `accounting:create_entry`.
     *     - `422 Unprocessable Entity` — schema validation failure.
     */
    post: operations["create_journal_entry_api_v1_accounting_journal_entries_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/accounting/journal-entries/{entry_id}/post": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Post a draft journal entry to the ledger
     * @description Transitions a journal entry from **DRAFT** to **POSTED** status, making it an immutable, auditable record in the General Ledger.
     *
     *     **Required permission:** `accounting:post`
     *
     *     **Business rules:**
     *     - Only entries in DRAFT status can be posted.
     *     - Total debits must equal total credits (balanced entry).
     *     - Once posted, the entry cannot be modified — only voided.
     *     - The `posted_by` user ID is recorded for audit trail.
     *
     *     **Error scenarios:**
     *     - `400 Bad Request` — entry is not in DRAFT status or is unbalanced.
     *     - `403 Forbidden` — caller lacks `accounting:post`.
     *     - `404 Not Found` — entry ID does not exist.
     */
    post: operations["post_journal_entry_api_v1_accounting_journal_entries__entry_id__post_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/accounting/journal-entries/{entry_id}/void": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Void a posted journal entry
     * @description Voids an existing **POSTED** journal entry, effectively reversing its impact on the ledger while maintaining an audit trail.  Voiding is only possible for posted entries.
     *
     *     **Required permission:** `accounting:void`
     *
     *     **Business rules:**
     *     - Only entries in POSTED status can be voided.
     *     - Once voided, an entry cannot be un-voided or modified.
     *     - A mandatory reason must be provided for the audit log.
     *
     *     **Error scenarios:**
     *     - `400 Bad Request` — entry is not in POSTED status.
     *     - `403 Forbidden` — caller lacks `accounting:void`.
     *     - `404 Not Found` — entry ID does not exist.
     */
    post: operations["void_journal_entry_api_v1_accounting_journal_entries__entry_id__void_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/accounting/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all GL accounts for the current tenant
     * @description Returns the complete Chart of Accounts for the authenticated user's tenant, including account codes, types, and hierarchy.
     *
     *     **Required permission:** `accounting:view`
     *
     *     **Business rules:**
     *     - Results are scoped to the caller's tenant — no cross-tenant access.
     *     - Both active and inactive accounts are returned.
     *     - Accounts are categorised as: Asset, Liability, Equity, Revenue, or Expense.
     *
     *     **Error scenarios:**
     *     - `401 Unauthorized` — missing or invalid Bearer token.
     *     - `403 Forbidden` — caller lacks `accounting:view`.
     */
    get: operations["list_accounts_api_v1_accounting_accounts_get"];
    put?: never;
    /**
     * Create a new GL account in the Chart of Accounts
     * @description Adds a new General Ledger account to the tenant's Chart of Accounts. Accounts form a tree structure via optional `parent_id`.
     *
     *     **Required permission:** `accounting:manage_accounts`
     *
     *     **Business rules:**
     *     - Account codes must be unique within the tenant.
     *     - Valid account types: `Asset`, `Liability`, `Equity`, `Revenue`, `Expense`.
     *     - If `parent_id` is provided, it must reference an existing account of the same type.
     *     - New accounts default to active status.
     *
     *     **Idempotency:** Supports the `Idempotency-Key` header.
     *
     *     **Error scenarios:**
     *     - `400 Bad Request` — duplicate code or invalid parent reference.
     *     - `403 Forbidden` — caller lacks `accounting:manage_accounts`.
     *     - `422 Unprocessable Entity` — schema validation failure.
     */
    post: operations["create_account_api_v1_accounting_accounts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/accounting/accounts/{account_id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Deactivate a GL account
     * @description Disables an account in the Chart of Accounts, preventing any future postings.  The account and its historical transactions remain in the ledger for reporting and audit purposes.
     *
     *     **Required permission:** `accounting:manage_accounts`
     *
     *     **Business rules:**
     *     - Deactivated accounts are hidden from standard account selectors.
     *     - Existing journal entries referencing this account are not affected.
     *
     *     **Error scenarios:**
     *     - `403 Forbidden` — caller lacks `accounting:manage_accounts`.
     *     - `404 Not Found` — account ID does not exist.
     */
    post: operations["deactivate_account_api_v1_accounting_accounts__account_id__deactivate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/accounting/accounts/{account_id}/rename": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rename a GL account
     * @description Updates the human-readable name of an account.  The unique code and historical data remain unchanged.
     *
     *     **Required permission:** `accounting:manage_accounts`
     *
     *     **Error scenarios:**
     *     - `400 Bad Request` — name is empty or invalid.
     *     - `403 Forbidden` — caller lacks `accounting:manage_accounts`.
     */
    post: operations["rename_account_api_v1_accounting_accounts__account_id__rename_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/approvals/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Approvals module health check
     * @description Returns a simple status indicator confirming the Approvals module is loaded and responsive.  This endpoint requires authentication and is intended for internal diagnostics.
     *
     *     **Required permission:** Any authenticated user.
     *
     *     **Note:** This is a placeholder endpoint. Full approval workflow CRUD endpoints (define policies, list pending approvals, etc.) will be added in a future release.
     */
    get: operations["health_check_api_v1_approvals_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List payment requests for the current user
     * @description Returns all payment requests created by the authenticated user within their tenant, ordered by creation date descending.
     *
     *     **Required permission:** Any authenticated user.
     *
     *     **Business rules:**
     *     - Only requests owned by the caller are returned.
     *     - Results include requests in all statuses (DRAFT, SUBMITTED, APPROVED, REJECTED, PAID).
     *
     *     **Error scenarios:**
     *     - `401 Unauthorized` — missing or invalid Bearer token.
     */
    get: operations["list_my_requests_api_v1_payment_requests_get"];
    put?: never;
    /**
     * Create a new payment request
     * @description Initiates a new payment request in **DRAFT** status. The request captures the beneficiary, amount, currency, and business justification for the payment.
     *
     *     **Required permission:** Any authenticated user (requester).
     *
     *     **Business rules:**
     *     - The request is created in DRAFT status — it must be explicitly submitted for approval.
     *     - The `requester_id` is automatically set to the authenticated user.
     *     - Amount must be a positive number.
     *     - Currency defaults to `ETB` (Ethiopian Birr) if not specified.
     *     - An optional `bank_account_id` pre-selects the disbursement account.
     *
     *     **Idempotency:** Supports the `Idempotency-Key` header.
     *
     *     **Error scenarios:**
     *     - `400 Bad Request` — invalid beneficiary or bank account reference.
     *     - `401 Unauthorized` — missing or invalid Bearer token.
     *     - `422 Unprocessable Entity` — schema validation failure.
     */
    post: operations["create_payment_request_api_v1_payment_requests_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-requests/{pr_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve a specific payment request
     * @description Fetches the full details of a payment request by its UUID, including current status, approval step, and assigned approver.
     *
     *     **Required permission:** Any authenticated user within the tenant.
     *
     *     **Error scenarios:**
     *     - `401 Unauthorized` — missing or invalid Bearer token.
     *     - `404 Not Found` — payment request does not exist or belongs to a different tenant.
     */
    get: operations["get_payment_request_api_v1_payment_requests__pr_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-requests/{pr_id}/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a draft payment request for approval
     * @description Transition a payment request from **DRAFT** to **SUBMITTED** status and initiate the multi-step approval workflow.
     *
     *     **Required permission:** Requester (owner) of the request.
     */
    post: operations["submit_payment_request_api_v1_payment_requests__pr_id__submit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-requests/{pr_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve a submitted payment request
     * @description Advances a payment request through its approval workflow.  If this is the final approval step, the status transitions to **APPROVED**.
     *
     *     **Required permission:** Assigned approver for the current step.
     */
    post: operations["approve_payment_request_api_v1_payment_requests__pr_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-requests/{pr_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reject a submitted payment request
     * @description Transitions a payment request from **SUBMITTED** to **REJECTED** status.  A reason must be provided for the requester.
     *
     *     **Required permission:** Assigned approver for the current step.
     */
    post: operations["reject_payment_request_api_v1_payment_requests__pr_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-requests/{pr_id}/pay": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark an approved payment request as paid
     * @description Finalizes the lifecycle of an **APPROVED** payment request by marking it as **PAID**.  Finance users typically perform this action after executing the actual disbursement (e.g., bank transfer).
     *
     *     **Required permission:** Finance / Disbursement officer.
     */
    post: operations["pay_payment_request_api_v1_payment_requests__pr_id__pay_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reporting/cashflow/daily": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get daily cashflow summary
     * @description Returns denormalized daily cashflow aggregates (inflow/outflow) for a date range.
     */
    get: operations["get_daily_cashflow_api_v1_reporting_cashflow_daily_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/webhooks/subscriptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all webhook subscriptions
     * @description Retrieves all active and inactive webhook subscriptions configured for the current tenant.
     */
    get: operations["list_subscriptions_api_v1_webhooks_subscriptions_get"];
    put?: never;
    /**
     * Create a new webhook subscription
     * @description Registers a URL to receive signed POST notifications when specific domain events occur within the tenant.
     *
     *     **Required permission:** Administrator / System Integration.
     */
    post: operations["create_subscription_api_v1_webhooks_subscriptions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/webhooks/subscriptions/{subscription_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Deactivate a webhook subscription
     * @description Permanently removes a webhook subscription. The external system will no longer receive domain events.
     */
    delete: operations["delete_subscription_api_v1_webhooks_subscriptions__subscription_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/ingest/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Ingest Chart of Accounts
     * @description Rapid-ingest historical GL Accounts from legacy systems.
     *     Bypasses standard DDD validation constraints, assuming external data sanitization.
     */
    post: operations["bulk_ingest_accounts_api_v1_system_ingest_accounts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/ingest/journal-entries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Ingest Historical Ledger Balances
     * @description Rapid-ingest pre-balanced historical journal entries and ledger lines.
     *     Executes raw SQL block pushes to achieve orders of magnitude faster imports than single events.
     */
    post: operations["bulk_ingest_journal_entries_api_v1_system_ingest_journal_entries_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Application health check
     * @description Returns a simple JSON status indicating the API process is running and able to serve requests.  This endpoint requires **no authentication** and is intended for load-balancer and container-orchestrator liveness probes.
     */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AccountCreate
     * @description Request body for creating a new GL account.
     */
    AccountCreate: {
      /**
       * Code
       * @description Numeric account code.  Must be unique within the tenant's Chart of Accounts.  Follow your organisation's numbering convention (e.g. 1xxx = Assets, 2xxx = Liabilities).
       * @example 1010
       */
      code: number;
      /**
       * Name
       * @description Descriptive name for the account.
       * @example Petty Cash
       */
      name: string;
      /**
       * Account Type
       * @description Account classification: `Asset`, `Liability`, `Equity`, `Revenue`, or `Expense`.
       * @example Asset
       */
      account_type: string;
      /**
       * Parent Id
       * @description Optional parent account UUID for hierarchical nesting. The parent must be of the same account type.
       */
      parent_id?: string | null;
    };
    /**
     * AccountRead
     * @description Read model for a General Ledger account in the Chart of Accounts.
     */
    AccountRead: {
      /**
       * Id
       * Format: uuid
       * @description Unique identifier of the GL account (UUID v7).
       */
      id: string;
      /**
       * Code
       * @description Numeric account code following the organisation's chart structure. Typically 4-6 digits (e.g. 1000 = Cash, 4000 = Revenue).
       * @example 1000
       */
      code: number;
      /**
       * Name
       * @description Human-readable account name.
       * @example Cash and Cash Equivalents
       */
      name: string;
      /**
       * Account Type
       * @description Classification of the account. One of: `Asset`, `Liability`, `Equity`, `Revenue`, `Expense`.
       * @example Asset
       */
      account_type: string;
      /**
       * Parent Id
       * @description UUID of the parent account for hierarchical grouping. `null` indicates a top-level account.
       */
      parent_id?: string | null;
      /**
       * Is Active
       * @description Whether the account can receive new postings.
       */
      is_active: boolean;
    };
    /**
     * AccountRename
     * @description Request body for renaming a GL account.
     */
    AccountRename: {
      /**
       * Name
       * @description New descriptive name for the account.
       * @example Petty Cash - Main Office
       */
      name: string;
    };
    /** AccountsImportRequest */
    AccountsImportRequest: {
      /**
       * Items
       * @description List of raw Account rows.
       */
      items: {
        [key: string]: unknown;
      }[];
    };
    /** Body_login_api_v1_auth_login_post */
    Body_login_api_v1_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** BulkImportResponse */
    BulkImportResponse: {
      /**
       * Success
       * @default true
       */
      success: boolean;
      /** Imported Rows */
      imported_rows: number;
    };
    /**
     * CreateTenantRequest
     * @description Request body for provisioning a new tenant organisation.
     */
    CreateTenantRequest: {
      /**
       * Name
       * @description Display name for the new tenant organisation. Must be unique across the entire platform.
       * @example Addis Manufacturing PLC
       */
      name: string;
      /**
       * Features
       * @description Optional set of feature flags to enable/disable on creation.
       * @example {
       *       "accounting": true,
       *       "webhooks": true
       *     }
       */
      features?: {
        [key: string]: boolean;
      } | null;
    };
    /**
     * CreateTenantResponse
     * @description Response returned after a tenant is successfully provisioned.
     */
    CreateTenantResponse: {
      /**
       * Tenant Id
       * Format: uuid
       * @description UUID v7 identifier assigned to the newly created tenant.
       * @example 019524f5-9a3c-7d2e-b145-68c3a7e1f9d0
       */
      tenant_id: string;
    };
    /**
     * CreateUserRequest
     * @description Request body for creating a new user within a tenant.
     */
    CreateUserRequest: {
      /**
       * Email
       * Format: email
       * @description Email address used as the user's login identifier. Must be unique within the tenant.
       * @example admin@addis-manufacturing.com
       */
      email: string;
      /**
       * Password
       * @description Plaintext password that will be hashed with bcrypt before storage. Must be at least 8 characters.
       * @example S3cureP@ssw0rd!
       */
      password: string;
    };
    /**
     * CreateUserResponse
     * @description Response returned after a user is successfully created.
     */
    CreateUserResponse: {
      /**
       * User Id
       * Format: uuid
       * @description UUID v7 identifier assigned to the newly created user.
       * @example 019524f5-b1a2-7e3f-c256-79d4b8f2a0e1
       */
      user_id: string;
    };
    /**
     * DailyCashflowDTO
     * @description Data Transfer Object for daily cashflow summary.
     */
    DailyCashflowDTO: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Total Inflow */
      total_inflow: number;
      /** Total Outflow */
      total_outflow: number;
      /** Net Cashflow */
      net_cashflow: number;
      /** Currency Code */
      currency_code: string;
    };
    /**
     * ErrorResponse
     * @description Standard error envelope returned by domain exception handlers.
     */
    ErrorResponse: {
      /**
       * Success
       * @description Always false for error responses.
       * @default false
       */
      success: boolean;
      /**
       * Detail
       * @description Human-readable error message describing what went wrong.
       * @example Journal entry with identifier 'abc-123' not found
       */
      detail: string;
      /**
       * Code
       * @description Machine-readable error code for programmatic handling. One of: DOMAIN_ERROR, NOT_FOUND, CONFLICT, FORBIDDEN, VALIDATION_ERROR, INVARIANT_VIOLATION.
       * @example NOT_FOUND
       */
      code: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** JournalEntriesImportRequest */
    JournalEntriesImportRequest: {
      /**
       * Entries
       * @description List of raw JournalEntry rows.
       */
      entries: {
        [key: string]: unknown;
      }[];
      /**
       * Lines
       * @description List of raw JournalLine rows mapping entry_ids.
       */
      lines: {
        [key: string]: unknown;
      }[];
    };
    /**
     * JournalEntryCreate
     * @description Request body for creating a new journal entry.
     */
    JournalEntryCreate: {
      /**
       * Date
       * Format: date
       * @description Transaction date in ISO 8601 format (YYYY-MM-DD).
       * @example 2026-03-18
       */
      date: string;
      /**
       * Description
       * @description Narrative description of the business transaction (3–500 characters).
       * @example Purchase of office supplies from Mega Stationery
       */
      description: string;
      /**
       * Base Currency
       * @description ISO 4217 code of the entry's functional (base) currency.
       * @default ETB
       * @example ETB
       */
      base_currency: string;
      /**
       * Lines
       * @description Ordered list of debit and credit lines.  A valid journal entry requires at least two lines (one debit and one credit).
       */
      lines: components["schemas"]["JournalLineCreate"][];
    };
    /**
     * JournalEntryRead
     * @description Read model for a complete journal entry with its line items.
     */
    JournalEntryRead: {
      /**
       * Id
       * Format: uuid
       * @description Unique identifier of the journal entry (UUID v7).
       */
      id: string;
      /**
       * Entry Number
       * @description Auto-generated human-readable entry number (format: `JV-XXXXXXXX`).
       * @example JV-A1B2C3D4
       */
      entry_number: string;
      /**
       * Date
       * Format: date
       * @description Transaction date (ISO 8601).
       * @example 2026-03-18
       */
      date: string;
      /**
       * Description
       * @description Narrative description of the transaction.
       */
      description: string;
      /**
       * Base Currency
       * @description Functional currency for the entry.
       * @example ETB
       */
      base_currency: string;
      /**
       * Status
       * @description Current status of the entry: `DRAFT` or `POSTED`.
       * @example DRAFT
       */
      status: string;
      /**
       * Lines
       * @description Ordered list of debit/credit lines comprising this entry.
       */
      lines: components["schemas"]["JournalLineRead"][];
    };
    /**
     * JournalEntryVoid
     * @description Request body for voiding a posted journal entry.
     */
    JournalEntryVoid: {
      /**
       * Reason
       * @description Reason for voiding the entry (auditable).
       * @example Mistake in amount
       * @example Duplicate entry
       */
      reason: string;
    };
    /**
     * JournalLineCreate
     * @description A single debit or credit line within a journal entry creation request.
     */
    JournalLineCreate: {
      /**
       * Account Id
       * Format: uuid
       * @description UUID of the GL account to debit or credit.
       */
      account_id: string;
      /**
       * Description
       * @description Optional memo for this individual line item (max 500 characters).
       * @example Office supplies purchase
       */
      description?: string | null;
      /**
       * Amount
       * @description Monetary amount for this line in the specified currency.  Must be positive — direction is determined by `is_debit`.
       * @example 1500.00
       */
      amount: number | string;
      /**
       * Currency
       * @description ISO 4217 currency code for this line.  Multi-currency lines are converted to the entry's base currency at the prevailing rate.
       * @default ETB
       * @example ETB
       */
      currency: string;
      /**
       * Is Debit
       * @description `true` for a debit entry, `false` for a credit entry.  The sum of all debits must equal the sum of all credits for the parent journal entry to be postable.
       * @default true
       */
      is_debit: boolean;
    };
    /**
     * JournalLineRead
     * @description Read model for a single line within a posted or draft journal entry.
     */
    JournalLineRead: {
      /**
       * Id
       * Format: uuid
       * @description Unique identifier of the journal line.
       */
      id: string;
      /**
       * Account Id
       * Format: uuid
       * @description GL account UUID this line posts to.
       */
      account_id: string;
      /**
       * Description
       * @description Optional line-level memo.
       */
      description?: string | null;
      /**
       * Amount
       * @description Amount in the line's original currency.
       * @example 1500.00
       */
      amount: string;
      /**
       * Currency
       * @description ISO 4217 currency code of the line amount.
       * @example ETB
       */
      currency: string;
      /**
       * Amount In Base
       * @description Amount converted to the entry's base currency.
       * @example 1500.00
       */
      amount_in_base: string;
      /**
       * Exchange Rate
       * @description Exchange rate applied for the conversion (1.0 if same currency).
       * @example 1.000000
       */
      exchange_rate: string;
      /**
       * Is Debit
       * @description `true` if this is a debit line, `false` if credit.
       */
      is_debit: boolean;
    };
    /**
     * PaymentRequestCreateDTO
     * @description Request body for creating a new payment request.
     */
    PaymentRequestCreateDTO: {
      /**
       * Beneficiary Id
       * Format: uuid
       * @description UUID of the beneficiary (payee) who will receive the payment.
       */
      beneficiary_id: string;
      /**
       * Amount
       * @description Monetary amount to be paid.  Must be a positive number.  Precision is determined by the currency's decimal places.
       * @example 25000
       */
      amount: number;
      /**
       * Currency
       * @description ISO 4217 currency code for the payment amount.
       * @default ETB
       * @example ETB
       */
      currency: string;
      /**
       * Justification
       * @description Business justification explaining why this payment is required.  Reviewed by approvers during the approval workflow.
       * @example Monthly office rent — March 2026
       */
      justification: string;
      /**
       * Bank Account Id
       * @description Optional UUID of the bank account from which the payment should be disbursed.  If omitted, finance selects at payment time.
       */
      bank_account_id?: string | null;
    };
    /**
     * PaymentRequestDTO
     * @description Read model representing a payment request with its current lifecycle state.
     */
    PaymentRequestDTO: {
      /**
       * Id
       * Format: uuid
       * @description Unique identifier of the payment request (UUID v7).
       */
      id: string;
      /**
       * Requester Id
       * Format: uuid
       * @description UUID of the user who created this request.
       */
      requester_id: string;
      /**
       * Beneficiary Id
       * Format: uuid
       * @description UUID of the beneficiary (payee).
       */
      beneficiary_id: string;
      /**
       * Amount
       * @description Payment amount in the specified currency.
       * @example 25000
       */
      amount: number;
      /**
       * Currency
       * @description ISO 4217 currency code.
       * @example ETB
       */
      currency: string;
      /**
       * Justification
       * @description Business justification provided by the requester.
       */
      justification: string;
      /**
       * @description Current lifecycle status: `DRAFT`, `SUBMITTED`, `APPROVED`, `REJECTED`, or `PAID`.
       * @example DRAFT
       */
      status: components["schemas"]["PaymentRequestStatus"];
      /**
       * Bank Account Id
       * @description UUID of the selected disbursement bank account, if any.
       */
      bank_account_id?: string | null;
      /**
       * Submitted At
       * @description Timestamp when the request was submitted for approval (ISO 8601).
       */
      submitted_at?: string | null;
      /**
       * Paid At
       * @description Timestamp when the payment was disbursed (ISO 8601).
       */
      paid_at?: string | null;
      /**
       * Current Approval Step
       * @description Zero-based index of the current approval step in the workflow.  Increments as each approver advances the request.
       * @example 0
       */
      current_approval_step: number;
      /**
       * Assigned Approver Id
       * @description UUID of the user currently assigned to approve this step.
       */
      assigned_approver_id?: string | null;
    };
    /**
     * PaymentRequestPayDTO
     * @description Request body for marking an approved request as paid.
     */
    PaymentRequestPayDTO: {
      /**
       * Payment Method
       * @description Method used for disbursement (e.g. BANK_TRANSFER, CHECK, CASH).
       * @example BANK_TRANSFER
       */
      payment_method: string;
      /**
       * Disbursement Reference
       * @description External transaction reference or confirmation number.
       * @example TRX-2026-0318-99
       */
      disbursement_reference: string;
    };
    /**
     * PaymentRequestRejectDTO
     * @description Request body for rejecting a payment request (requires reason).
     */
    PaymentRequestRejectDTO: {
      /**
       * Reason
       * @description Reason for rejecting the request (reviewed by requester).
       * @example Budget allocation exceeded for Q1
       */
      reason: string;
    };
    /**
     * PaymentRequestStatus
     * @enum {string}
     */
    PaymentRequestStatus: "DRAFT" | "SUBMITTED" | "APPROVED" | "REJECTED" | "PAID";
    /**
     * SetupRequest
     * @description Request body for the one-time ERP bootstrap operation.
     */
    SetupRequest: {
      /**
       * Tenant Name
       * @description Display name for the organisation to provision.
       * @example Addis Manufacturing PLC
       */
      tenant_name: string;
      /**
       * Admin Email
       * Format: email
       * @description Email address for the initial administrator account.
       * @example admin@addis-manufacturing.com
       */
      admin_email: string;
      /**
       * Admin Password
       * @description Password for the initial administrator (hashed on creation).
       * @example S3cureP@ssw0rd!
       */
      admin_password: string;
    };
    /**
     * SetupResponse
     * @description Response confirming both tenant and admin user were created.
     */
    SetupResponse: {
      /**
       * Tenant Id
       * Format: uuid
       * @description UUID v7 of the provisioned tenant.
       * @example 019524f5-9a3c-7d2e-b145-68c3a7e1f9d0
       */
      tenant_id: string;
      /**
       * User Id
       * Format: uuid
       * @description UUID v7 of the admin user created within the tenant.
       * @example 019524f5-b1a2-7e3f-c256-79d4b8f2a0e1
       */
      user_id: string;
    };
    /**
     * TokenDTO
     * @description Auth token response containing JWT access and refresh tokens.
     */
    TokenDTO: {
      /**
       * Access Token
       * @description Short-lived JWT access token.  Include as `Authorization: Bearer <token>` on subsequent requests.  Contains claims: `sub`, `tenant_id`, `email`, `roles`, `permissions`.
       */
      access_token: string;
      /**
       * Refresh Token
       * @description Long-lived refresh token (7-day expiry) used to obtain a new access token via the `/auth/refresh` endpoint.
       */
      refresh_token?: string | null;
      /**
       * Token Type
       * @description Token type — always `"bearer"` per OAuth 2.0 specification.
       * @default bearer
       */
      token_type: string;
    };
    /**
     * UserProfileDTO
     * @description CQRS read model for a user's profile.
     */
    UserProfileDTO: {
      /**
       * Id
       * Format: uuid
       * @description Unique identifier of the user (UUID v7).
       */
      id: string;
      /**
       * Tenant Id
       * Format: uuid
       * @description Identifier of the tenant this user belongs to.
       */
      tenant_id: string;
      /**
       * Email
       * @description User's email address (login identifier).
       * @example admin@addis-manufacturing.com
       */
      email: string;
      /**
       * Is Active
       * @description Whether the user account is currently active and can authenticate.
       */
      is_active: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * ValidationErrorDetail
     * @description Individual field-level validation error (FastAPI / Pydantic 422).
     */
    ValidationErrorDetail: {
      /**
       * Loc
       * @description JSON path to the invalid field (e.g. ['body', 'amount']).
       * @example [
       *       "body",
       *       "amount"
       *     ]
       */
      loc: (string | number)[];
      /**
       * Msg
       * @description Validation error message.
       * @example value is not a valid float
       */
      msg: string;
      /**
       * Type
       * @description Error type identifier from the validation backend.
       * @example value_error
       */
      type: string;
    };
    /**
     * ValidationErrorResponse
     * @description HTTP 422 response body produced by FastAPI request validation.
     */
    ValidationErrorResponse: {
      /**
       * Success
       * @description Always false for error responses.
       * @default false
       */
      success: boolean;
      /**
       * Detail
       * @description List of per-field validation errors.
       */
      detail: components["schemas"]["ValidationErrorDetail"][];
    };
    /**
     * WebhookSubscriptionCreateDTO
     * @description Request body for creating a new webhook subscription.
     */
    WebhookSubscriptionCreateDTO: {
      /**
       * Event Type
       * @description Type of event to subscribe to (e.g., 'JOURNAL_ENTRY_POSTED', 'PAYMENT_APPROVED', or '*' for all).
       * @example JOURNAL_ENTRY_POSTED
       */
      event_type: string;
      /**
       * Target Url
       * @description External HTTP URL where the signed JSON payload will be POSTed.
       * @example https://api.external-partner.com/webhooks/abren
       */
      target_url: string;
      /**
       * Description
       * @description Optional internal description for this subscription.
       * @example Integration with Partner X Accounting Service
       */
      description?: string | null;
    };
    /**
     * WebhookSubscriptionDTO
     * @description Read model for a webhook subscription.
     */
    WebhookSubscriptionDTO: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Event Type */
      event_type: string;
      /** Target Url */
      target_url: string;
      /** Secret */
      secret: string;
      /** Is Active */
      is_active: boolean;
      /** Description */
      description: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  create_tenant_api_v1_core_tenants_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTenantRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateTenantResponse"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  create_user_api_v1_core_users_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateUserResponse"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  setup_erp_api_v1_core_setup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetupRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetupResponse"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  read_users_me_api_v1_core_users_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserProfileDTO"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Resource not found.** The requested entity does not exist or does not belong to the current tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenDTO"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  refresh_token_api_v1_auth_refresh_post: {
    parameters: {
      query: {
        refresh_token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenDTO"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_journal_entry_api_v1_accounting_journal_entries_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JournalEntryCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JournalEntryRead"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  post_journal_entry_api_v1_accounting_journal_entries__entry_id__post_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JournalEntryRead"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Resource not found.** The requested entity does not exist or does not belong to the current tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  void_journal_entry_api_v1_accounting_journal_entries__entry_id__void_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JournalEntryVoid"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JournalEntryRead"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  list_accounts_api_v1_accounting_accounts_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountRead"][];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_account_api_v1_accounting_accounts_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountRead"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  deactivate_account_api_v1_accounting_accounts__account_id__deactivate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountRead"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  rename_account_api_v1_accounting_accounts__account_id__rename_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountRename"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountRead"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  health_check_api_v1_approvals_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  list_my_requests_api_v1_payment_requests_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentRequestDTO"][];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_payment_request_api_v1_payment_requests_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentRequestCreateDTO"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentRequestDTO"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  get_payment_request_api_v1_payment_requests__pr_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pr_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentRequestDTO"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Resource not found.** The requested entity does not exist or does not belong to the current tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_payment_request_api_v1_payment_requests__pr_id__submit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pr_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  approve_payment_request_api_v1_payment_requests__pr_id__approve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pr_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  reject_payment_request_api_v1_payment_requests__pr_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pr_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentRequestRejectDTO"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  pay_payment_request_api_v1_payment_requests__pr_id__pay_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pr_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentRequestPayDTO"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  get_daily_cashflow_api_v1_reporting_cashflow_daily_get: {
    parameters: {
      query: {
        start_date: string;
        end_date: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DailyCashflowDTO"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_subscriptions_api_v1_webhooks_subscriptions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WebhookSubscriptionDTO"][];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_subscription_api_v1_webhooks_subscriptions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WebhookSubscriptionCreateDTO"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WebhookSubscriptionDTO"];
        };
      };
      /** @description **Bad request.** The request could not be processed due to a domain-level business rule violation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Insufficient permissions.** The authenticated user does not hold the required RBAC permission for this operation. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Validation error.** One or more request fields failed schema or business-rule validation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  delete_subscription_api_v1_webhooks_subscriptions__subscription_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        subscription_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description **Authentication required.** The request lacks a valid Bearer token or the token has expired. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description **Resource not found.** The requested entity does not exist or does not belong to the current tenant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bulk_ingest_accounts_api_v1_system_ingest_accounts_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountsImportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BulkImportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bulk_ingest_journal_entries_api_v1_system_ingest_journal_entries_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JournalEntriesImportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
